### ISSUE TITLE
[Support] Using concrete PHP version for running PhpStan

### ISSUE THREAD

**Issue by lisachenko** [chindit/actions-phpstan#1]
Hello! I'm checking if there is a way to run this action with concrete PHP version (7.4), defined in my action and not PHP8, which is used now by default.

See failing analysis: https://github.com/goaop/framework/runs/2273225976?check_suite_focus=true
Unfortunately, parser reflection library is not compatible with PHP8, thus analysis is failing. And this will be true for this major version all the time. As I'm going to maintain it, it is very important for me to control PHP version used for analysis.

Definition of GH action workflow for PhpStan: https://github.com/goaop/framework/blob/master/.github/workflows/phpstan.yml

**Comment by lisachenko** [comment]
Ping @chindit ?

**Comment by chindit** [comment]
Hmmmm.
The easiest way is to use version 1.0.1 and not master.
You still have the latest version of PHPStan but the action will use PHP 7.4
So, just change you line to 
`uses: chindit/actions-phpstan@1.0.1`

It's not easy to change the action to support a version parameter because it's based on a docker image specific for each PHP version.  

I'll think about it, but the quickest fix it to use v1.0.1.  The only difference between this version and `master` is the switch to PHP 8.0

**Comment by lisachenko** [comment]
Ok, got it, thank you! 

Maybe just to maintain several major branches with different PHP versions then and document this? Otherwise there are chances to break existing pipelines that depend on this action when upgrading it to new versions of PHP.
